include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    use_key_in_widget_constructors: false
    prefer_const_constructors_in_immutables: false
    sort_child_properties_last: false
    sized_box_for_whitespace: false
    avoid_unnecessary_containers: false
    use_super_parameters: false
